package main

// TypeScript type generation: /p/{slug}/types.ts renders the public schema as
// a supabase-js-compatible Database interface (Tables Row/Insert/Update,
// Views, Enums), so typed clients autocomplete against the live schema.

import (
	"fmt"
	"net/http"
	"sort"
	"strings"
)

// tsType maps a Postgres data type to its TypeScript counterpart.
func tsType(c tableCol, enums map[string][]string) string {
	t := strings.ToLower(c.Type)
	// enum columns carry their type name in Type (set by tableCols)
	if labels, ok := enums[c.Type]; ok && len(labels) > 0 {
		parts := make([]string, len(labels))
		for i, l := range labels {
			parts[i] = fmt.Sprintf("%q", l)
		}
		return strings.Join(parts, " | ")
	}
	switch {
	case t == "boolean":
		return "boolean"
	case t == "smallint", t == "integer", t == "real", t == "double precision":
		return "number"
	case t == "bigint", t == "numeric":
		return "number" // beware precision; matches supabase-js convention
	case t == "json", t == "jsonb":
		return "Json"
	case strings.HasPrefix(t, "timestamp"), t == "date", strings.HasPrefix(t, "time"):
		return "string"
	case t == "array":
		return elemTS(c.UDT) + "[]"
	default:
		return "string" // text, varchar, uuid, inet, bytea markers, everything else
	}
}

// elemTS maps an array's udt_name (e.g. _int4, _text) to the element type.
func elemTS(udt string) string {
	switch strings.TrimPrefix(udt, "_") {
	case "int2", "int4", "int8", "float4", "float8", "numeric":
		return "number"
	case "bool":
		return "boolean"
	case "json", "jsonb":
		return "Json"
	default:
		return "string"
	}
}

func (a *app) typesTS(w http.ResponseWriter, r *http.Request) {
	slug := r.PathValue("slug")
	db, err := a.dbFor(slug)
	if err != nil {
		http.Error(w, err.Error(), 500)
		return
	}
	enums := map[string][]string{}
	for _, e := range a.listEnums(db, "public") {
		enums[e.Name] = e.Labels
	}

	var b strings.Builder
	b.WriteString("// Generated by ForgeBase for project " + slug + " - regenerate after schema changes.\n")
	b.WriteString("export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]\n\n")
	b.WriteString("export interface Database {\n  public: {\n")

	var tables, views []string
	for _, rel := range a.listRelations(db, "public") {
		switch rel.Kind {
		case "table":
			tables = append(tables, rel.Name)
		case "view", "matview":
			views = append(views, rel.Name)
		}
	}

	b.WriteString("    Tables: {\n")
	for _, t := range tables {
		cols := a.tableCols(db, "public", t)
		fmt.Fprintf(&b, "      %s: {\n", tsKey(t))
		b.WriteString("        Row: {\n")
		for _, c := range cols {
			null := ""
			if c.Nullable == "YES" {
				null = " | null"
			}
			fmt.Fprintf(&b, "          %s: %s%s\n", tsKey(c.Name), tsType(c, enums), null)
		}
		b.WriteString("        }\n        Insert: {\n")
		for _, c := range cols {
			opt, null := "", ""
			if c.Nullable == "YES" {
				null = " | null"
			}
			if c.Nullable == "YES" || c.Default != "" {
				opt = "?"
			}
			fmt.Fprintf(&b, "          %s%s: %s%s\n", tsKey(c.Name), opt, tsType(c, enums), null)
		}
		b.WriteString("        }\n        Update: {\n")
		for _, c := range cols {
			null := ""
			if c.Nullable == "YES" {
				null = " | null"
			}
			fmt.Fprintf(&b, "          %s?: %s%s\n", tsKey(c.Name), tsType(c, enums), null)
		}
		b.WriteString("        }\n")
		var rels []string
		for _, c := range cols {
			if c.FKTable != "" {
				rels = append(rels, fmt.Sprintf(
					"          { foreignKeyName: %q, columns: [%q], referencedRelation: %q, referencedColumns: [%q] }",
					t+"_"+c.Name+"_fkey", c.Name, c.FKTable, c.FKCol))
			}
		}
		if len(rels) > 0 {
			b.WriteString("        Relationships: [\n" + strings.Join(rels, ",\n") + "\n        ]\n")
		} else {
			b.WriteString("        Relationships: []\n")
		}
		b.WriteString("      }\n")
	}
	b.WriteString("    }\n    Views: {\n")
	for _, v := range views {
		cols := a.tableCols(db, "public", v)
		fmt.Fprintf(&b, "      %s: {\n        Row: {\n", tsKey(v))
		for _, c := range cols {
			fmt.Fprintf(&b, "          %s: %s | null\n", tsKey(c.Name), tsType(c, enums))
		}
		b.WriteString("        }\n      }\n")
	}
	b.WriteString("    }\n    Enums: {\n")
	var enames []string
	for n := range enums {
		enames = append(enames, n)
	}
	sort.Strings(enames)
	for _, n := range enames {
		parts := make([]string, len(enums[n]))
		for i, l := range enums[n] {
			parts[i] = fmt.Sprintf("%q", l)
		}
		fmt.Fprintf(&b, "      %s: %s\n", tsKey(n), strings.Join(parts, " | "))
	}
	b.WriteString("    }\n  }\n}\n")

	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	if r.URL.Query().Get("dl") == "1" {
		w.Header().Set("Content-Disposition", `attachment; filename="database.types.ts"`)
	}
	w.Write([]byte(b.String()))
}

// tsKey renders an object key, quoting it when it is not a plain identifier.
func tsKey(s string) string {
	plain := len(s) > 0
	for i, r := range s {
		if r == '_' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || (i > 0 && r >= '0' && r <= '9') {
			continue
		}
		plain = false
		break
	}
	if plain {
		return s
	}
	return fmt.Sprintf("%q", s)
}
